# SeokHyeon Chin, 2016320179

## Getting Started

In [1]:
import torch

In [2]:
x = torch.arange(12) # if run without dtype
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.dtype # dtype default = int64

torch.int64

In [4]:
x = torch.arange(12, dtype=torch.float64)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [5]:
x.shape

torch.Size([12])

In [6]:
x.size() # Same as .shape

torch.Size([12])

In [7]:
x = x.reshape((3, 4))
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [8]:
x = x.reshape((3, 2, 2)) # Discussion: Can also have 3 dimensions or more
x

tensor([[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.]]], dtype=torch.float64)

In [9]:
x = x.reshape((3, -1)) # Can automatically infer what '-1' should be
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [10]:
torch.FloatTensor(2, 3) # Can be big or small number

tensor([[2.1122e+20, 8.5419e+20, 2.1668e-04],
        [4.2885e-08, 2.0890e+20, 3.3356e-09]])

In [11]:
torch.Tensor(2, 3)

tensor([[2.1122e+20, 8.5419e+20, 2.1668e-04],
        [4.2885e-08, 2.0890e+20, 3.3356e-09]])

In [12]:
torch.empty(2, 3) # Can be all zeros. Above 3 are the same

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.zeros((2, 3, 4)) # To make all zeros - initiation

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
torch.ones((2, 3, 4)) # Discussion: From number two, doesn't exist

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [16]:
torch.randn(3, 4)

tensor([[-0.6497,  0.9082, -0.2966, -0.6496],
        [ 1.8713, -1.2194, -0.6262, -0.9454],
        [-0.6216, -0.5456, -0.7611, -0.3458]])

## Operations

In [17]:
x = torch.tensor([1, 2, 4, 8], dtype=torch.float32)
y = torch.ones_like(x) * 2 # Makes same shape as x
print('x =', x)
print('x + y', x + y) # Same shape examples
print('x - y', x - y)
print('x * y', x * y)
print('x / y', x / y)

x = tensor([1., 2., 4., 8.])
x + y tensor([ 3.,  4.,  6., 10.])
x - y tensor([-1.,  0.,  2.,  6.])
x * y tensor([ 2.,  4.,  8., 16.])
x / y tensor([0.5000, 1.0000, 2.0000, 4.0000])


In [18]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [19]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=torch.float32)
print(x.dtype)
print(y)
torch.mm(x, y.t()) # Matrix multiplication

torch.float32
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[ 18.,  20.,  10.],
        [ 58.,  60.,  50.],
        [ 98., 100.,  90.]])

In [20]:
print(y.t()) # '.t()'is used to transpose a matrix

tensor([[2., 1., 4.],
        [1., 2., 3.],
        [4., 3., 2.],
        [3., 4., 1.]])


In [21]:
torch.cat((x, y), dim=0) # Merge along rows

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [22]:
torch.cat((x, y), dim=1) # Merge along columns

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [23]:
x == y # Same element: True, otherwise: False

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [24]:
x.sum()

tensor(66.)

## Broadcast Mechanism

In [25]:
a = torch.arange(3, dtype=torch.float).reshape((3, 1))
b = torch.arange(2, dtype=torch.float).reshape((1, 2))
a, b

(tensor([[0.],
         [1.],
         [2.]]), tensor([[0., 1.]]))

In [26]:
a + b # Different shape - broadcasting

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

## Indexing and Slicing

In [27]:
x[1:3] # Bring [2 <= x rows < 3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
x[0:2, :] = 12 # Discussion: Works also for more than 2 dimmensions
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [30]:
x[0:2, 0:2] = 25 # First element points row, 2nd element points column
x

tensor([[25., 25., 12., 12.],
        [25., 25., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [31]:
x[:,0:2] # To bring columns

tensor([[25., 25.],
        [25., 25.],
        [ 8.,  9.]])

## Saving Memory

In [32]:
before = id(y) # Discussion: Allocate in different memory by default
y = y + x
id(y) == before

False

In [33]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y # For in-place operation, but still temp memory for x+y needs
print('id(z):', id(z))

id(z): 2172451377704
id(z): 2172451377704


In [34]:
before = id(z)
torch.add(x, y, out=z) # No need temp memory for x+y 
id(z) == before

True

In [35]:
before = id(x)
x += y # Same as `x[:] = x + y`
id(x) == before

True

## Mutual Transformation of PyTorch and NumPy

In [36]:
a = x.numpy()
print(type(a))
b = torch.tensor(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


## Discussion
* `.reshape` and **Indexing and Slicing** works also for multiple dimensions.
* Why there's only `.zeros` and `.ones` to create tensors with all elements same?
* Why PyTorch doesn't have in-place operation by default while C language does?